#!/bin/bash

source ".env"
docker build . -t ${DOCKER_TAG_VERSION} -t ${DOCKER_TAG_LATEST}
docker run \
-p 8080:${DOCKER_PORT} \
	-e PORT=${DOCKER_PORT} \
    -e ENVIRONMENT="${ENVIRONMENT}" \
	-e DATABASE_HOST="${DATABASE_HOST}" \
	-e DATABASE_NAME="${DATABASE_NAME}" \
	-e DATABASE_USER="${DATABASE_USER}" \
	-e DATABASE_PASSWORD="${DATABASE_PASSWORD}" \
	-e DATABASE_SOCKET=${DATABASE_SOCKET} \
	-e DATABASE_SESSION_STORE_IN_DB=${DATABASE_SESSION_STORE_IN_DB} \
	-e DATABASE_SESSION_EXPIRES=${DATABASE_SESSION_EXPIRES} \
	${DOCKER_APP}